### ISSUE TITLE
add `pass` to generated class when message body is empty

### ISSUE THREAD

**Issue by hu6360567** [so1n/protobuf_to_pydantic#10]
**Is your feature request related to a problem? Please describe.**
When message is empty, the generated code is empty after class.
```protobuf
message Empty{}
message Something {
string s = 1;
}
```
Generated code is like
```
class Empty(BaseModel):


class Something(BaseModel):
    s : ...
```

**Describe the solution you'd like**
Add `pass` statement to generated class if the message body is empty

**Comment by so1n** [comment]
Thank you for your feedback, I will fix this in the next version (probably at the weekend)
