### ISSUE TITLE
Genereted code does not pass mypy

### ISSUE THREAD

**Issue by jankatins** [so1n/protobuf_to_pydantic#13]
**Describe the bug**
The generated code does not pass mypy checks, as the field line is generated as 

```py
    id: int = FieldInfo(default=0)
```

instead of 
```py
    id: int = Field(default=0)
```

```
λ  mypy protobuf_p2p.py
protobuf_p2p.py:8: error: Incompatible types in assignment (expression has type "FieldInfo", variable has type "int")  [assignment]
protobuf_p2p.py:9: error: Incompatible types in assignment (expression has type "FieldInfo", variable has type "int")  [assignment]
Found 2 errors in 1 file (checked 1 source file)
```

**Expected behavior**

The resulting file is mypy clean

**ideas**

I tried outputting `Fields` instead of `FieldInfo` in the two lines below and for my usecase, that was fine. 

https://github.com/so1n/protobuf_to_pydantic/blob/8c7adf6d33e7dda70184b5eaa9c871f67bb39916/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py#L269-L270

But I guess there might be content which does not fit into a `Field`, but only into a `FieldInfo`?

The other idea how to fix this would be to add a `# type: ignore[assignment]` (specific, because otherwise ruff complains...) in the generated field code:

https://github.com/so1n/protobuf_to_pydantic/blob/8c7adf6d33e7dda70184b5eaa9c871f67bb39916/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py#L278-L281

```diff
-            " " * (self.code_indent + indent) + f"{field.name}: {type_str} = {field_name}({field_info_str})\n"
+            " " * (self.code_indent + indent) + f"{field.name}: {type_str} = {field_name}({field_info_str}) # type: ignore[assignment]\n"
```

**relevant mypy config**

I use the pydantic mypy plugin:

```toml
[tool.mypy]
plugins = [
    # Better support for pydantic models
    "pydantic.mypy"
]
```

**Comment by so1n** [comment]
Thanks for your feedback, according to Pydantic's documentation, the output should be `Field` instead of `FieldInfo`, I need to correct it immediately
