### ISSUE TITLE
Typos in the word "pydantic" in the README.md file

### ISSUE THREAD

**Issue by Markovvn1** [so1n/protobuf_to_pydantic#16]
Both files (README.md and README_ZH.md) contain a typo in some of the words "pydantic". In some places it says "pydan**it**c":

> the command `python -m pip install protobuf-to-pydanitc[mypy-protobuf]`.

> indicates the use of the `prorobuf-to-pydanitc` plugin

**Comment by so1n** [comment]
Thanks for your feedback, I will edit it right away
