### ISSUE TITLE
Optional fields do not generate correct defaults in Pydantic

### ISSUE THREAD

**Issue by calclavia** [so1n/protobuf_to_pydantic#22]
**Describe the bug**
Using proto v3

Marking a field as optional in Proto doesn't seem to change anything in the generated Pydantic model.

**To Reproduce**
.proto
```
syntax = "proto3";

message A {
    string a = 1;
}
message B {
    optional A a = 1;
}
```

Output:
```
class A(BaseModel):
    a: str = Field(default="")

class B(BaseModel):
    a: typing.Optional[A] = Field()
```

**Expected behavior**
This is the expected output:
```
class A(BaseModel):
    a: str = Field(default="")


class B(BaseModel):
    a: typing.Optional[A] = Field(default=None)
```

Note that without setting `default = None` in Pydantic, it's impossible to construct `B()` with no args. You have to construct it via `B(a=None)`.

**Comment by so1n** [comment]
Thanks for the feedback, I will fix this in version 0.2.0.1.

**Comment by calclavia** [comment]
There's another bug that's caused by the fix.

For fields such as:
```
repeated string a = 1;
```

It now generates this:
```
a: typing.Optional[typing.List[str]] = Field(default_factory=list, default=None)
```
which is not allowed in Pydantic. You cannot have default_factory and a default.

**Comment by so1n** [comment]
> @so1n There's another bug created that's caused by the fix.
> 
> For fields such as:
> 
> ```
> repeated string a = 1;
> ```
> 
> It now generates this:
> 
> ```
> a: typing.Optional[typing.List[str]] = Field(default_factory=list, default=None)
> ```
> 
> which is not allowed in Pydantic. You cannot have default_factory and a default.

Please provide the Protobuf file or Message, I can't reproduce the problem at the moment

**Comment by calclavia** [comment]
@so1n Here it is:

```
syntax = "proto3";

message A {
    optional string a = 2;
    repeated string b = 3;
}
```

Output:
```
# This is an automatically generated file, please do not change
# gen by protobuf_to_pydantic[v0.2.0.1](https://github.com/so1n/protobuf_to_pydantic)
# Protobuf Version: 4.24.3
# Pydantic Version: 1.10.12
from google.protobuf.message import Message  # type: ignore
from pydantic import BaseModel
from pydantic import Field
import typing


class A(BaseModel):
    a: typing.Optional[str] = Field(default="")
    b: typing.Optional[typing.List[str]] = Field(default_factory=list, default=None)
```
