### ISSUE TITLE
Integrate plugin with buf cli

### ISSUE THREAD

**Issue by dwwhitlock** [so1n/protobuf_to_pydantic#26]
**Is your feature request related to a problem? Please describe.**
Our team is using the [buf cli](https://buf.build/docs/ecosystem/cli-overview) to manage protobuf builds because 
managing `protoc` calls can be clunky. 

**Describe the solution you'd like**
I'd like this plugin integrated with the [CodeGeneratorRequest](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/compiler/plugin.proto#L43) so that a [Dockerfile](https://buf.build/docs/bsr/remote-plugins/custom-plugins#build-a-docker-image) can be implemented that will allow a [custom plugin](https://buf.build/docs/bsr/remote-plugins/custom-plugins#creating-a-custom-plugin) to be implemented.

Additionally, this will facilitate adoption by Buf to make it a hosted plugin, which will likely increase adoption of this plugin.

**Describe alternatives you've considered**
The alternative is to use the CLI as documented. However, `buf generate` is a much friendlier interface to using this.

**Additional context**
https://github.com/bufbuild/plugins/issues/589

**Comment by so1n** [comment]
> **Is your feature request related to a problem? Please describe.** Our team is using the [buf cli](https://buf.build/docs/ecosystem/cli-overview) to manage protobuf builds because managing `protoc` calls can be clunky.
> 
> **Describe the solution you'd like** I'd like this plugin integrated with the [CodeGeneratorRequest](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/compiler/plugin.proto#L43) so that a [Dockerfile](https://buf.build/docs/bsr/remote-plugins/custom-plugins#build-a-docker-image) can be implemented that will allow a [custom plugin](https://buf.build/docs/bsr/remote-plugins/custom-plugins#creating-a-custom-plugin) to be implemented.
> 
> Additionally, this will facilitate adoption by Buf to make it a hosted plugin, which will likely increase adoption of this plugin.
> 
> **Describe alternatives you've considered** The alternative is to use the CLI as documented. However, `buf generate` is a much friendlier interface to using this.
> 
> **Additional context** [bufbuild/plugins#589](https://github.com/bufbuild/plugins/issues/589)

I'm sorry this is my first experience with `buf cli` and it will take some time to get used to it.
But the concept of `buf cli` is great and i will implement it sonn.

**Comment by so1n** [comment]
Currently,some changes that need to be made to make it compatible with the `buf cli`. Until then, you can use `protobuf-to-pydantic` via `buf-cli` with the instructions below.

Let's assume that the project is now structured as follows:
```
├── proto-demo
│   ├── buf.yaml  # gen by `npx buf mod init`
│   ├── common
│   │   ├── p2p_validate.proto 
│   │   └── validate.proto
│   └── demo.proto
├── buf.gen.yaml
├── plugin_config.py
└── pyproject.toml
```
Among them, `p2p_validate.proto` and `validate.proto` cloned from [github](https://github.com/so1n/protobuf_to_pydantic/tree/master/protos) to `proto-demo/common`.

The contents of the other documents are as follows:
- demo.proto
    ```protobuf
    syntax = "proto3";
    
    package demo;
    
    import "common/p2p_validate.proto";
    import "common/validate.proto";
    
    message p2p_demo{
      int32 a = 1[(p2p_validate.rules).int32.default=1];
    }
    
    message validate_demo{
      string b = 1[(validate.rules).string.max_len=3];
    }    
    ````
- plugin_config.py
    ```python
    from typing import List
    
    # Ignore files to prevent program errors
    ignore_pkg_list: List[str] = ["validate", "p2p_validate"]
    ```
- buf.gen.yaml
    ```yaml
    version: v1beta1
    plugins:
      - name: protobuf-to-pydantic
        out: proto_out
        opt:
          - paths=source_relative
          - config_path=plugin_config.py
    ```
- pyproject.toml
    ```toml
    ...
  
    [tool.poetry.dependencies]
    python = "^3.8"
    protobuf-to-pydantic = "^0.2.0.3"
    grpcio-tools = "^1.59.0"
    pydantic = "^2.4.2"
    mypy-protobuf = "^3.5.0"
    toml = "^0.10.2"
  
    ...
    ```

All the files are ready, install 'protoc' and 'buf' on the system.
Finally, can execute the 'protobuf-to-pydanitc' plugin  via `buf-cli` in the terminal.
```bash
# Set the current directory to the working directory to load the plugin_config.py
export PYTHONPATH=$PYTHONPATH:.
# Poetry can be used to load information into the current Python environment
poetry run npx buf generate proto-demo 
```
If 'poetry' is not installed, can directly activate the current python environment and execute the command, as follows
```bash
# Set the current directory to the working directory to load the plugin_config.py
export PYTHONPATH=$PYTHONPATH:.
# Suppose the path of the current python program is '.venv/bin/python'
source .venv/bin/activate
npx buf generate proto-demo
```
