### ISSUE TITLE
Oneof for non primitive types

### ISSUE THREAD

**Issue by anotherchudov** [so1n/protobuf_to_pydantic#31]
**Describe the bug**
Unusable pydantic model is generated.

**To Reproduce**
```
syntax = "proto3";
message A {
  bool a = 1;
}
message B {
  bool b = 1;
}
message C {
  oneof z {
    A a = 1;
    B b = 2;
  }
  optional B c = 3;
}
```

generates this:
```
class A(BaseModel):
    a: bool = Field(default=False)


class B(BaseModel):
    b: bool = Field(default=False)


class C(BaseModel):
    _one_of_dict = {"C._c": {"fields": {"c"}}, "C.z": {"fields": {"a", "b"}}}
    one_of_validator = model_validator(mode="before")(check_one_of)

    a: A = Field()
    b: B = Field()
    c: typing.Optional[B] = Field(default=None)
```

**Expected behavior**
```
class A(BaseModel):
    a: bool = Field(default=False)


class B(BaseModel):
    b: bool = Field(default=False)


class C(BaseModel):
    _one_of_dict = {"C._c": {"fields": {"c"}}, "C.z": {"fields": {"a", "b"}}}
    one_of_validator = model_validator(mode="before")(check_one_of)

    a: typing.Optional[A] = Field(default=None)
    b: typing.Optional[B] = Field(default=None)
    c: typing.Optional[B] = Field(default=None)
```

**Comment by so1n** [comment]
@anotherchudov 

If want fields a,b to be optional, then the contents of the protobuf should be changed to the following:
```protobuf
syntax = "proto3";
message A {
  bool a = 1;
}
message B {
  bool b = 1;
}
message C {
  oneof z {
    optional A a = 1;
    optional B b = 2;
  }
  optional B c = 3;
}
```
But Protobuf doesn't support this syntax, I will consider another way to support a,b fields as optional, as follows:
```protobuf
syntax = "proto3";
message A {
  bool a = 1;
}
message B {
  bool b = 1;
}
message C {
  oneof z {
    option (p2p_validate.optional) = ["a", "b"];

    A a = 1;
    B b = 2;
  }
  optional B c = 3;
}
```
This feature will be implemented in the next version.

**Comment by ditsuke** [comment]
@so1n by definition, doesn't `oneof` mean that all fields should be optional given one exists?

**Comment by so1n** [comment]
@ditsuke In Protobuf, oneof simply restricts a set of fields to only one that has a value, while other fields have default values (not null).

For example:
```Protobuf
message OneOfOptionalTest {
  string header = 1;
  oneof id {
    string x = 2;
    int32  y = 3;
    bool z = 4;
  }
  optional string name = 5;
  optional int32 age= 6;
  repeated string str_list = 7;
  map<string, int32> int_map = 8;
}
```
The type of each property in the Python object generated by OneOfOptional is as follows:

|field | type|
|---|---|
|x|str|
|y|int|
|z|bool|
|name|str , None|
|age|int, None|
|str_list| list[str]|
|int_map|dict[str, int]|

At runtime:
```Python
>>> demo1 = OneOfOptionalTest(x="1")
>>> demo1.x
... '1'
>>> demo2 = OneOfOptionalTest(x="1", y=2)
>>> demo2.x
... ''
>>> demo2.y
... 2
>>> demo3 = OneOfOptionalTest(name=None, age=3)
>>> demo3.name
... ''
>>> demo3.age
... 3
```

**Comment by jafaircl** [comment]
@so1n the issue described still doesn't work. The tests added by the PR only test for primitive oneof types. Nested messages in a oneof are still broken even with the annotation in the proto file.

**Comment by so1n** [comment]
> @so1n the issue described still doesn't work. The tests added by the PR only test for primitive oneof types. Nested messages in a oneof are still broken even with the annotation in the proto file.

I've fixed this issue, and after enough unit testing I'll release an update. see: https://github.com/so1n/protobuf_to_pydantic/issues/55
