### ISSUE TITLE
Missing typing import for optional field

### ISSUE THREAD

**Issue by jankatins** [so1n/protobuf_to_pydantic#38]
**Describe the bug**

The following (shortend) proto file creates a non-valid pydantic python file:

```proto
syntax = "proto3";
package whatever.v1;

message Blub {
  int64 whatever = 1;
}

message CheckCreateCommitFromPreparationResponse {
  optional Blub blib = 1;
}
```

Converting with protobuf-to-pydantic gives this

```py
# This is an automatically generated file, please do not change
# gen by protobuf_to_pydantic[v0.2.3](https://github.com/so1n/protobuf_to_pydantic)
# Protobuf Version: 4.25.2 
# Pydantic Version: 2.6.1 
from google.protobuf.message import Message  # type: ignore
from pydantic import BaseModel
from pydantic import Field


class Blub(BaseModel):

    whatever: int = Field(default=0) 


class CheckCreateCommitFromPreparationResponse(BaseModel):

    blib: typing.Optional[Blub] = Field(default=None) 
```

Which misses the import for typing and therefore the last lines errors on import.

**To Reproduce**
1. Install the above versions (see python version)
2. convert proto to pydantic
3. try to import the pydantic file
4. See error: `NameError: name 'typing' is not defined. Did you forget to import 'typing'`

**Expected behavior**
There is a typing import in the generated file and I can import the generated file without an error

**Comment by so1n** [comment]
Thank you for your feedback, the fix was a few days late as I was on vacation (Chinese New Year).
