### ISSUE TITLE
reorder generated classes to avoid unresolved references

### ISSUE THREAD

**Issue by qai222** [so1n/protobuf_to_pydantic#4]
Thanks for the nice module!

**Is your feature request related to a problem? Please describe.**
The order of generated `pydantic` classes (from `python -m grpc_tools.protoc -I. --protobuf-to-pydantic_out=. example.proto`) can cause unresolved references: a class definition comes after its references in other classes.

**Describe the solution you'd like**
I'm using the following script to reorder generated classes, but it may be better to integrate this step.

```python
import ast

def reorder_classes(source):
    tree = ast.parse(source)

    # Extract the classes from the AST and sort them topologically
    class_nodes = [node for node in tree.body if isinstance(node, ast.ClassDef)]
    class_dependencies = {}
    for class_node in class_nodes:
        class_dependencies[class_node] = {
            dep.id for dep in ast.walk(class_node) if
            isinstance(dep, ast.Name) and dep.id in [cls.name for cls in class_nodes]
        }
    sorted_classes = []
    while class_dependencies:
        acyclic_nodes = [node for node, deps in class_dependencies.items() if not deps]
        if not acyclic_nodes:
            raise ValueError('Circular dependency found')
        for node in acyclic_nodes:
            del class_dependencies[node]
            sorted_classes.append(node)
            for deps in class_dependencies.values():
                deps.discard(node.name)

    # Rewrite the source code with the sorted classes
    sorted_source = '\n\n'.join([ast.unparse(node) for node in sorted_classes])
    return sorted_source
```

**Comment by so1n** [comment]
> Thanks for the nice module!
> 
> **Is your feature request related to a problem? Please describe.** The order of generated `pydantic` classes (from `python -m grpc_tools.protoc -I. --protobuf-to-pydantic_out=. example.proto`) can cause unresolved references: a class definition comes after its references in other classes.
> 
> **Describe the solution you'd like** I'm using the following script to reorder generated classes, but it may be better to integrate this step.
> 
> ```python
> import ast
> 
> def reorder_classes(source):
>     tree = ast.parse(source)
> 
>     # Extract the classes from the AST and sort them topologically
>     class_nodes = [node for node in tree.body if isinstance(node, ast.ClassDef)]
>     class_dependencies = {}
>     for class_node in class_nodes:
>         class_dependencies[class_node] = {
>             dep.id for dep in ast.walk(class_node) if
>             isinstance(dep, ast.Name) and dep.id in [cls.name for cls in class_nodes]
>         }
>     sorted_classes = []
>     while class_dependencies:
>         acyclic_nodes = [node for node, deps in class_dependencies.items() if not deps]
>         if not acyclic_nodes:
>             raise ValueError('Circular dependency found')
>         for node in acyclic_nodes:
>             del class_dependencies[node]
>             sorted_classes.append(node)
>             for deps in class_dependencies.values():
>                 deps.discard(node.name)
> 
>     # Rewrite the source code with the sorted classes
>     sorted_source = '\n\n'.join([ast.unparse(node) for node in sorted_classes])
>     return sorted_source
> ```

Thanks for your feedback, this is something I hadn't considered, I will integrate this feature into the project

**Comment by so1n** [comment]
Thank you for your feedback. After testing, I found that the problem you described did not occur, and the problem may be caused by a scenario I did not consider. Please provide the Protobuf file for testing, thank you!

**Comment by so1n** [comment]
I have pushed the changes to the [branch](https://github.com/so1n/protobuf_to_pydantic/tree/4-reorder-generated-classes-to-avoid-unresolved-references), you can clone it locally for verification
