### ISSUE TITLE
dependencies clash with protobuf-5.26.1

### ISSUE THREAD

**Issue by PeterBosch2** [so1n/protobuf_to_pydantic#48]
Adding `protobuf>=5` together with the latest `protobuf-to-pydantic` to a python project clashes, as dependecy constraints are contradicting.

Because no versions of grpcio-tools match >1.40.0,<1.41.0 || >1.41.0,<1.41.1 || >1.41.1,<1.42.0 || >1.42.0,<1.43.0 || >1.43.0,<1.44.0 || >1.44.0,<1.45.0 || >1.45.0,<1.46.0 || >1.46.0,<1.46.1 || >1.46.1,<1.46.3 || >1.46.3,<1.46.5 || >1.46.5,<1.47.0 || >1.47.0,<1.47.2 || >1.47.2,<1.47.5 || >1.47.5,<1.48.0 || >1.48.0,<1.48.1 || >1.48.1,<1.48.2 || >1.48.2,<1.49.0 || >1.49.0,<1.49.1 || >1.49.1,<1.50.0 || >1.50.0,<1.51.0 || >1.51.0,<1.51.1 || >1.51.1,<1.51.3 || >1.51.3,<1.52.0 || >1.52.0,<1.53.0 || >1.53.0,<1.53.1 || >1.53.1,<1.53.2 || >1.53.2,<1.54.0rc1 || >1.54.0rc1,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.0rc2 || >1.56.0rc2,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0
 and grpcio-tools (1.54.0rc1) depends on protobuf (>=4.21.6,<5.0dev), grpcio-tools (>1.40.0,<1.41.0 || >1.41.0,<1.41.1 || >1.41.1,<1.42.0 || >1.42.0,<1.43.0 || >1.43.0,<1.44.0 || >1.44.0,<1.45.0 || >1.45.0,<1.46.0 || >1.46.0,<1.46.1 || >1.46.1,<1.46.3 || >1.46.3,<1.46.5 || >1.46.5,<1.47.0 || >1.47.0,<1.47.2 || >1.47.2,<1.47.5 || >1.47.5,<1.48.0 || >1.48.0,<1.48.1 || >1.48.1,<1.48.2 || >1.48.2,<1.49.0 || >1.49.0,<1.49.1 || >1.49.1,<1.50.0 || >1.50.0,<1.51.0 || >1.51.0,<1.51.1 || >1.51.1,<1.51.3 || >1.51.3,<1.52.0 || >1.52.0,<1.53.0 || >1.53.0,<1.53.1 || >1.53.1,<1.53.2 || >1.53.2,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.0rc2 || >1.56.0rc2,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=4.21.6,<5.0dev).
And because grpcio-tools (1.56.0rc2) depends on protobuf (>=4.21.6,<5.0dev), grpcio-tools (>1.40.0,<1.41.0 || >1.41.0,<1.41.1 || >1.41.1,<1.42.0 || >1.42.0,<1.43.0 || >1.43.0,<1.44.0 || >1.44.0,<1.45.0 || >1.45.0,<1.46.0 || >1.46.0,<1.46.1 || >1.46.1,<1.46.3 || >1.46.3,<1.46.5 || >1.46.5,<1.47.0 || >1.47.0,<1.47.2 || >1.47.2,<1.47.5 || >1.47.5,<1.48.0 || >1.48.0,<1.48.1 || >1.48.1,<1.48.2 || >1.48.2,<1.49.0 || >1.49.0,<1.49.1 || >1.49.1,<1.50.0 || >1.50.0,<1.51.0 || >1.51.0,<1.51.1 || >1.51.1,<1.51.3 || >1.51.3,<1.52.0 || >1.52.0,<1.53.0 || >1.53.0,<1.53.1 || >1.53.1,<1.53.2 || >1.53.2,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=4.21.6,<5.0dev).
And because grpcio-tools (1.40.0) depends on protobuf (>=3.5.0.post1,<4.0dev)
 and grpcio-tools (1.41.0) depends on protobuf (>=3.5.0.post1,<4.0dev), grpcio-tools (>=1.40.0,<1.41.1 || >1.41.1,<1.42.0 || >1.42.0,<1.43.0 || >1.43.0,<1.44.0 || >1.44.0,<1.45.0 || >1.45.0,<1.46.0 || >1.46.0,<1.46.1 || >1.46.1,<1.46.3 || >1.46.3,<1.46.5 || >1.46.5,<1.47.0 || >1.47.0,<1.47.2 || >1.47.2,<1.47.5 || >1.47.5,<1.48.0 || >1.48.0,<1.48.1 || >1.48.1,<1.48.2 || >1.48.2,<1.49.0 || >1.49.0,<1.49.1 || >1.49.1,<1.50.0 || >1.50.0,<1.51.0 || >1.51.0,<1.51.1 || >1.51.1,<1.51.3 || >1.51.3,<1.52.0 || >1.52.0,<1.53.0 || >1.53.0,<1.53.1 || >1.53.1,<1.53.2 || >1.53.2,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.6,<5.0dev).
And because grpcio-tools (1.41.1) depends on protobuf (>=3.5.0.post1,<4.0dev)
 and grpcio-tools (1.42.0) depends on protobuf (>=3.5.0.post1,<4.0dev), grpcio-tools (>=1.40.0,<1.43.0 || >1.43.0,<1.44.0 || >1.44.0,<1.45.0 || >1.45.0,<1.46.0 || >1.46.0,<1.46.1 || >1.46.1,<1.46.3 || >1.46.3,<1.46.5 || >1.46.5,<1.47.0 || >1.47.0,<1.47.2 || >1.47.2,<1.47.5 || >1.47.5,<1.48.0 || >1.48.0,<1.48.1 || >1.48.1,<1.48.2 || >1.48.2,<1.49.0 || >1.49.0,<1.49.1 || >1.49.1,<1.50.0 || >1.50.0,<1.51.0 || >1.51.0,<1.51.1 || >1.51.1,<1.51.3 || >1.51.3,<1.52.0 || >1.52.0,<1.53.0 || >1.53.0,<1.53.1 || >1.53.1,<1.53.2 || >1.53.2,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.6,<5.0dev).
And because grpcio-tools (1.43.0) depends on protobuf (>=3.5.0.post1,<4.0dev)
 and grpcio-tools (1.44.0) depends on protobuf (>=3.5.0.post1,<4.0dev), grpcio-tools (>=1.40.0,<1.45.0 || >1.45.0,<1.46.0 || >1.46.0,<1.46.1 || >1.46.1,<1.46.3 || >1.46.3,<1.46.5 || >1.46.5,<1.47.0 || >1.47.0,<1.47.2 || >1.47.2,<1.47.5 || >1.47.5,<1.48.0 || >1.48.0,<1.48.1 || >1.48.1,<1.48.2 || >1.48.2,<1.49.0 || >1.49.0,<1.49.1 || >1.49.1,<1.50.0 || >1.50.0,<1.51.0 || >1.51.0,<1.51.1 || >1.51.1,<1.51.3 || >1.51.3,<1.52.0 || >1.52.0,<1.53.0 || >1.53.0,<1.53.1 || >1.53.1,<1.53.2 || >1.53.2,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.6,<5.0dev).
And because grpcio-tools (1.45.0) depends on protobuf (>=3.5.0.post1,<4.0dev)
 and grpcio-tools (1.46.0) depends on protobuf (>=3.12.0,<4.0dev), grpcio-tools (>=1.40.0,<1.46.1 || >1.46.1,<1.46.3 || >1.46.3,<1.46.5 || >1.46.5,<1.47.0 || >1.47.0,<1.47.2 || >1.47.2,<1.47.5 || >1.47.5,<1.48.0 || >1.48.0,<1.48.1 || >1.48.1,<1.48.2 || >1.48.2,<1.49.0 || >1.49.0,<1.49.1 || >1.49.1,<1.50.0 || >1.50.0,<1.51.0 || >1.51.0,<1.51.1 || >1.51.1,<1.51.3 || >1.51.3,<1.52.0 || >1.52.0,<1.53.0 || >1.53.0,<1.53.1 || >1.53.1,<1.53.2 || >1.53.2,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.6,<5.0dev).
And because grpcio-tools (1.46.1) depends on protobuf (>=3.12.0,<4.0dev)
 and grpcio-tools (1.46.3) depends on protobuf (>=3.12.0,<4.0dev), grpcio-tools (>=1.40.0,<1.46.5 || >1.46.5,<1.47.0 || >1.47.0,<1.47.2 || >1.47.2,<1.47.5 || >1.47.5,<1.48.0 || >1.48.0,<1.48.1 || >1.48.1,<1.48.2 || >1.48.2,<1.49.0 || >1.49.0,<1.49.1 || >1.49.1,<1.50.0 || >1.50.0,<1.51.0 || >1.51.0,<1.51.1 || >1.51.1,<1.51.3 || >1.51.3,<1.52.0 || >1.52.0,<1.53.0 || >1.53.0,<1.53.1 || >1.53.1,<1.53.2 || >1.53.2,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.6,<5.0dev).
And because grpcio-tools (1.46.5) depends on protobuf (>=3.12.0,<4.0dev)
 and grpcio-tools (1.47.0) depends on protobuf (>=3.12.0,<4.0dev), grpcio-tools (>=1.40.0,<1.47.2 || >1.47.2,<1.47.5 || >1.47.5,<1.48.0 || >1.48.0,<1.48.1 || >1.48.1,<1.48.2 || >1.48.2,<1.49.0 || >1.49.0,<1.49.1 || >1.49.1,<1.50.0 || >1.50.0,<1.51.0 || >1.51.0,<1.51.1 || >1.51.1,<1.51.3 || >1.51.3,<1.52.0 || >1.52.0,<1.53.0 || >1.53.0,<1.53.1 || >1.53.1,<1.53.2 || >1.53.2,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.6,<5.0dev).
And because grpcio-tools (1.47.2) depends on protobuf (>=3.12.0,<4.0dev)
 and grpcio-tools (1.47.5) depends on protobuf (>=3.12.0,<4.0dev), grpcio-tools (>=1.40.0,<1.48.0 || >1.48.0,<1.48.1 || >1.48.1,<1.48.2 || >1.48.2,<1.49.0 || >1.49.0,<1.49.1 || >1.49.1,<1.50.0 || >1.50.0,<1.51.0 || >1.51.0,<1.51.1 || >1.51.1,<1.51.3 || >1.51.3,<1.52.0 || >1.52.0,<1.53.0 || >1.53.0,<1.53.1 || >1.53.1,<1.53.2 || >1.53.2,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.6,<5.0dev).
And because grpcio-tools (1.48.0) depends on protobuf (>=3.12.0,<4.0dev)
 and grpcio-tools (1.48.1) depends on protobuf (>=3.12.0,<4.0dev), grpcio-tools (>=1.40.0,<1.48.2 || >1.48.2,<1.49.0 || >1.49.0,<1.49.1 || >1.49.1,<1.50.0 || >1.50.0,<1.51.0 || >1.51.0,<1.51.1 || >1.51.1,<1.51.3 || >1.51.3,<1.52.0 || >1.52.0,<1.53.0 || >1.53.0,<1.53.1 || >1.53.1,<1.53.2 || >1.53.2,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.6,<5.0dev).
And because grpcio-tools (1.48.2) depends on protobuf (>=3.12.0,<4.0dev)
 and grpcio-tools (1.49.0) depends on protobuf (>=4.21.3,<5.0dev), grpcio-tools (>=1.40.0,<1.49.1 || >1.49.1,<1.50.0 || >1.50.0,<1.51.0 || >1.51.0,<1.51.1 || >1.51.1,<1.51.3 || >1.51.3,<1.52.0 || >1.52.0,<1.53.0 || >1.53.0,<1.53.1 || >1.53.1,<1.53.2 || >1.53.2,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.3,<5.0dev).
And because grpcio-tools (1.49.1) depends on protobuf (>=4.21.3,<5.0dev)
 and grpcio-tools (1.50.0) depends on protobuf (>=4.21.6,<5.0dev), grpcio-tools (>=1.40.0,<1.51.0 || >1.51.0,<1.51.1 || >1.51.1,<1.51.3 || >1.51.3,<1.52.0 || >1.52.0,<1.53.0 || >1.53.0,<1.53.1 || >1.53.1,<1.53.2 || >1.53.2,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.3,<5.0dev).
And because grpcio-tools (1.51.0) depends on protobuf (>=4.21.6,<5.0dev)
 and grpcio-tools (1.51.1) depends on protobuf (>=4.21.6,<5.0dev), grpcio-tools (>=1.40.0,<1.51.3 || >1.51.3,<1.52.0 || >1.52.0,<1.53.0 || >1.53.0,<1.53.1 || >1.53.1,<1.53.2 || >1.53.2,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.3,<5.0dev).
And because grpcio-tools (1.51.3) depends on protobuf (>=4.21.6,<5.0dev)
 and grpcio-tools (1.52.0) depends on protobuf (>=4.21.6,<5.0dev), grpcio-tools (>=1.40.0,<1.53.0 || >1.53.0,<1.53.1 || >1.53.1,<1.53.2 || >1.53.2,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.3,<5.0dev).
And because grpcio-tools (1.53.0) depends on protobuf (>=4.21.6,<5.0dev)
 and grpcio-tools (1.53.1) depends on protobuf (>=4.21.6,<5.0dev), grpcio-tools (>=1.40.0,<1.53.2 || >1.53.2,<1.54.3 || >1.54.3,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.3,<5.0dev).
And because grpcio-tools (1.53.2) depends on protobuf (>=4.21.6,<5.0dev)
 and grpcio-tools (1.54.3) depends on protobuf (>=4.21.6,<5.0dev), grpcio-tools (>=1.40.0,<1.55.0 || >1.55.0,<1.55.3 || >1.55.3,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.3,<5.0dev).
And because grpcio-tools (1.55.0) depends on protobuf (>=4.21.6,<5.0dev)
 and grpcio-tools (1.55.3) depends on protobuf (>=4.21.6,<5.0dev), grpcio-tools (>=1.40.0,<1.56.2 || >1.56.2,<1.57.0 || >1.57.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.3,<5.0dev).
And because grpcio-tools (1.56.2) depends on protobuf (>=4.21.6,<5.0dev)
 and grpcio-tools (1.57.0) depends on protobuf (>=4.21.6,<5.0dev), grpcio-tools (>=1.40.0,<1.58.0 || >1.58.0,<1.59.0 || >1.59.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.3,<5.0dev).
And because grpcio-tools (1.58.0) depends on protobuf (>=4.21.6,<5.0dev)
 and grpcio-tools (1.59.0) depends on protobuf (>=4.21.6,<5.0dev), grpcio-tools (>=1.40.0,<1.59.2 || >1.59.2,<1.59.3 || >1.59.3,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.3,<5.0dev).
And because grpcio-tools (1.59.2) depends on protobuf (>=4.21.6,<5.0dev)
 and grpcio-tools (1.59.3) depends on protobuf (>=4.21.6,<5.0dev), grpcio-tools (>=1.40.0,<1.60.0 || >1.60.0,<1.60.1 || >1.60.1,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.3,<5.0dev).
And because grpcio-tools (1.60.0) depends on protobuf (>=4.21.6,<5.0dev)
 and grpcio-tools (1.60.1) depends on protobuf (>=4.21.6,<5.0dev), grpcio-tools (>=1.40.0,<1.62.0 || >1.62.0,<1.62.1 || >1.62.1,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.3,<5.0dev).
And because grpcio-tools (1.62.0) depends on protobuf (>=4.21.6,<5.0dev)
 and grpcio-tools (1.62.1) depends on protobuf (>=4.21.6,<5.0dev), grpcio-tools (>=1.40.0,<2.0.0) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.3,<5.0dev).
Because no versions of protobuf-to-pydantic match >0.2.6
 and protobuf-to-pydantic[mypy-protobuf] (0.2.6) depends on grpcio-tools (>=1.40.0,<2.0.0), protobuf-to-pydantic[mypy-protobuf] (>=0.2.6) requires grpcio-tools (>=1.40.0,<2.0.0).
Thus, protobuf-to-pydantic[mypy-protobuf] (>=0.2.6) requires protobuf (>=3.5.0.post1,<4.0dev || >=4.21.3,<5.0dev).
So, because mds-schema depends on both protobuf (>=5) and protobuf-to-pydantic[mypy-protobuf] (>=0.2.6), version solving failed.

**Comment by so1n** [comment]
@PeterBosch2 This problem is caused by the grpcio-tools(protobuf-to-pydantic needs it), and can only be solved by grpcio-tools.  see [grpc #36142](https://github.com/grpc/grpc/issues/36142)  and [grpcio_tools/setup.py#L332](https://github.com/grpc/grpc/blob/master/tools/distrib/python/grpcio_tools/setup.py#L332)

**Comment by so1n** [comment]
@PeterBosch2  After looking at the dependency tree, I realized that protobuf-to-pydantic doesn't need a dependency to grpcio-tools. i will release a new version to fix this.
