### ISSUE TITLE
Replace deprecated `FieldValidationInfo` with `ValidationInfo` in customer validator

### ISSUE THREAD

**Issue by chrisjz** [so1n/protobuf_to_pydantic#54]
**Describe the bug**

When we upgraded to `pydantic` v2.7.1, there are deprecation warnings surfaced from the customer validator in this package.

The solution should be to replace `FieldValidationInfo` with `ValidationInfo`.

Further details on the deprecation:
https://docs.pydantic.dev/latest/concepts/validators/#field-validators

**Comment by so1n** [comment]
Pydantic v2 has been having a lot of breaking updates, I will fix this in the next version
