### ISSUE TITLE
Plugin Mode support  text annotation rule

### ISSUE THREAD

**Issue by so1n** [so1n/protobuf_to_pydantic#55]
- 1: Plugin Mode support text annotation rule
- 2: fix proto_parse not support oneof comment

**Comment by so1n** [comment]
> Hi would you have an ETA for this release?
> 
> I am having the same issue as discussed here: #31

It's been a busy time lately, so I expect it to be done within two weeks

**Comment by so1n** [comment]
> Hi would you have an ETA for this release?
> 
> I am having the same issue as discussed here: #31

This ISSUE has been fixed and released to version 0.2.7, however the documentation has not been updated, please refer to the example code to use the text annotation rule.

**Comment by terrypireaux** [comment]
Could you point me to the specific example code?

**Comment by terrypireaux** [comment]
> > Hi would you have an ETA for this release?
> > I am having the same issue as discussed here: #31
> 
> This ISSUE has been fixed and released to version 0.2.7, however the documentation has not been updated, please refer to the example code to use the text annotation rule.

Could you point me to the specific example code?

**Comment by so1n** [comment]
> > > Hi would you have an ETA for this release?
> > > I am having the same issue as discussed here: #31
> > 
> > 
> > This ISSUE has been fixed and released to version 0.2.7, however the documentation has not been updated, please refer to the example code to use the text annotation rule.
> 
> Could you point me to the specific example code?

see https://github.com/so1n/protobuf_to_pydantic/blob/master/example/example_proto/p2p_validate_by_comment/demo.proto
