### ISSUE TITLE
The generation logic for import statements has issues in some cases

### ISSUE THREAD

**Issue by kasegao** [so1n/protobuf_to_pydantic#62]
**Describe the bug**

The `_add_other_module_pkg` function in `protobuf_to_pydantic/plugin/field_desc_proto_to_code.py` has issues in some cases. Specifically, in cases where the top-level paths are different and the intermediate paths match, the generated relative import paths are not appropriate.

**To Reproduce**

Consider the following directory structure. Both files share the intermediate path `v1`.

```sh
.
├─ app/v1/app.proto
└─ shared/v1/types.proto
```

`app/v1/app.proto`

```proto
syntax = "proto3";

package user.v1;

import "shared/v1/types.proto";

service AppService {
  rpc GetMe(GetMeRequest) returns (GetMeResponse);
}

message GetMeRequest {}
message GetMeResponse {
  shared.v1.UserType user_type = 1;
  string name = 2;
  int32 age = 3;
}
```

` shared/v1/types.proto`

```proto
syntax = "proto3";

package shared.v1;

enum UserType {
  USER_TYPE_UNSPECIFIED = 0;
  USER_TYPE_NORMAL = 1;
  USER_TYPE_GUEST = 2;
}
```

When generating Pydantic code for these files, the following files are created:

`app/v1/app_p2p.py`

```py
from .types_p2p import UserType
from google.protobuf.message import Message  # type: ignore
from pydantic import BaseModel
from pydantic import Field


class GetMeRequest(BaseModel):    pass

class GetMeResponse(BaseModel):
    user_type: UserType = Field(default=0)
    name: str = Field(default="")
    age: int = Field(default=0)
```

`shared/v1/types_p2p.py`

```py
from enum import IntEnum
from pydantic import BaseModel

class UserType(IntEnum):
    USER_TYPE_UNSPECIFIED = 0
    USER_TYPE_NORMAL = 1
    USER_TYPE_GUEST = 2
```

However, the import statement in the first line of `app/v1/app_p2p.py` fails to resolve the relative path correctly.

```py
from .types_p2p import UserType
```

**Expected behavior**

~I suggest specifying the path from the project root instead of using a relative path. In that case, the previously mentioned import statement should preferably be~

<strike>

```py
from shared.v1.types_p2p import UserType
```

</strike>

Expectied import path:

```py
from ...shared.v1.types_p2p import UserType
```

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Version MacBook Pro M3 Max (2023)

**Comment by kasegao** [comment]
I'm sorry, but the expected behavior I originally wrote was inappropriate, so I updated it.

**Comment by so1n** [comment]
Thank you very much for your feedback. There is no problem with this code in the current example proto. Can you add the corresponding proto to the example in the project and execute it? It would be great if you could add corresponding test cases  @kasegao

**Comment by hizbiz** [comment]
Thanks a lot for fixing the issue.
