### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in __instancecheck__

### ISSUE THREAD

**Issue by pppwaw** [so1n/protobuf_to_pydantic#7]
**Describe the bug**
After update proto in #2 , I tried to parse my proto, and I get this error

**Error Log**

> maximum recursion depth exceeded in __instancecheck__
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/main.py", line 12, in main
>     CodeGen(ConfigModel)
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/code_gen.py", line 30, in __init__
>     self.generate_pydantic_model(Descriptors(request), response)
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/code_gen.py", line 82, in generate_pydantic_model
>     file.content = self.config.file_descriptor_proto_to_code(
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 57, in __init__
>     self._parse_field_descriptor()
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 405, in _parse_field_descriptor
>     self._content_deque.append(self._message(desc, [FileDescriptorProto.ENUM_TYPE_FIELD_NUMBER]))
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 321, in _message
>     _content_tuple: Optional[Tuple[str, str]] = self._message_field_handle(
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 168, in _message_field_handle
>     self._content_deque.append(self._message(message, [FileDescriptorProto.ENUM_TYPE_FIELD_NUMBER]))
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 321, in _message
>     _content_tuple: Optional[Tuple[str, str]] = self._message_field_handle(
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 168, in _message_field_handle
>     self._content_deque.append(self._message(message, [FileDescriptorProto.ENUM_TYPE_FIELD_NUMBER]))
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 321, in _message
>     _content_tuple: Optional[Tuple[str, str]] = self._message_field_handle(
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 168, in _message_field_handle
>     self._content_deque.append(self._message(message, [FileDescriptorProto.ENUM_TYPE_FIELD_NUMBER]))
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 321, in _message
>     _content_tuple: Optional[Tuple[str, str]] = self._message_field_handle(
> 
>   ......
> 
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 168, in _message_field_handle
>     self._content_deque.append(self._message(message, [FileDescriptorProto.ENUM_TYPE_FIELD_NUMBER]))
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 321, in _message
>     _content_tuple: Optional[Tuple[str, str]] = self._message_field_handle(
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 183, in _message_field_handle
>     protobuf_type_model = self._get_protobuf_type_model(field)
>   File "/usr/local/lib/python3.9/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 359, in _get_protobuf_type_model
>     return ProtobufTypeModel(
>   File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
>   File "pydantic/main.py", line 1076, in pydantic.main.validate_model
>   File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
>   File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
>   File "pydantic/fields.py", line 1151, in pydantic.fields.ModelField._apply_validators
>   File "pydantic/class_validators.py", line 337, in pydantic.class_validators._generic_validator_basic.lambda13
>   File "pydantic/validators.py", line 61, in pydantic.validators.str_validator
> RecursionError: maximum recursion depth exceeded in __instancecheck__
>

**Comment by pppwaw** [comment]
```protobuf
syntax = "proto3";

message InvoiceItem {
  string name = 1;
  int32 amount = 2; 
  int32 quantity = 3;
  repeated InvoiceItem items = 4;
}
```
It can reproduces the problem.
In pydantic, it can can be solve by [This page](https://docs.pydantic.dev/usage/postponed_annotations/)

Also: 
1. the 15 line in code_gen.py , it's `if __version__ < "4.0.0":`, it should be `if __version__ > "4.0.0":`
2. Should we add a `pass` to a message that does not contain any fields?

**Comment by so1n** [comment]
> ```proto
> syntax = "proto3";
> 
> message InvoiceItem {
>   string name = 1;
>   int32 amount = 2; 
>   int32 quantity = 3;
>   repeated InvoiceItem items = 4;
> }
> ```
> 
> It can reproduces the problem. In pydantic, it can can be solve by [This page](https://docs.pydantic.dev/usage/postponed_annotations/)
> 
> Also:
> 
> 1. the 15 line in code_gen.py , it's `if __version__ < "4.0.0":`, it should be `if __version__ > "4.0.0":`
> 2. Should we add a `pass` to a message that does not contain any fields?

Thank you for the Protobuf file, I will fix this over the weekend and add enough tests to cover the different versions of the Protobuf pkg
