### ISSUE TITLE
Fields with enum type

### ISSUE THREAD

**Issue by jmspereira** [so1n/protobuf_to_pydantic#81]
Hey everyone,

I have a message where one of the fields is a protobuf enum, however, when converted for pydantic model, the valid enum values are the enum's values (the numeric values). What is the cleanest way of having the enum with the name of the fields instead of the values?

For instance, in your example:

```
enum SexType {
  man = 0;
  women = 1;
}
```

The enum values should be "man" and "women" instead of 0 and 1.
Thank you!

**Comment by so1n** [comment]
This question already has the same issue, see #61 .    At the same time, I am also considering using [check_one_of](https://github.com/so1n/protobuf_to_pydantic/blob/master/protobuf_to_pydantic/customer_validator/rule.py#L30) to convert the str enum to an int enum in advance, and then hand it over to pydantic for processing.
